name: CD

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [20.13]
        pnpm-version: [9.1]

    name: 📦️ Build abi.js.org on ${{ matrix.node-version }}-${{ matrix.operating-system }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ⚡️ Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: ${{ matrix.node-version }}
          package-manager: pnpm@${{ matrix.pnpm-version }}

  deploy:
    needs: build

    runs-on: ${{ matrix.operating-system }}

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    name: 🚀 Deploy abi.js.org on ${{ matrix.node-version }}-${{ matrix.operating-system }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 📂 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
