name: CD

on:
  push:
    # Trigger the workflow every time you push to the `trunk` branch
    branches:
      - trunk
    paths:
      - website/**
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [20.16]
        bun-version: [1.1.24]

    name: 📦️ Build abi.js.org on ${{ matrix.node-version }} with Bun@${{ matrix.bun-version }} under ${{ matrix.operating-system }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🍱 Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: ./website
          node-version: ${{ matrix.node-version }}
          package-manager: bun@${{ matrix.bun-version }}

  deploy:
    needs: build

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    name: Deploy abi.js.org 🚀

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 📂 Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/trunk'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          destination_dir: .
          external_repository: abi-js/abi-js.github.io
